<?php # -*- coding: utf-8 -*-

namespace InpsydeBoilerplate;

use
	BrightNucleus\Boilerplate\Scripts,
	BrightNucleus\Exception;

/**
 * Class Validation
 *
 * @package InpsydeBoilerplate
 */
class Validation extends Scripts\Validation {

	/**
	 * Verify that a string is in lowercase or throw an Exception.
	 *
	 * @param string $string The string to validate.
	 *
	 * @return string The validated string.
	 * @throws Exception\InvalidArgumentException If the string is not in lowercase.
	 */
	public static function validateLowerCase( $string ) {

		if ( $string === Scripts\SetupHelper::getLowerCase( $string ) ) {

			return $string;
		}

		return parent::validateLowerCase( $string ); // TODO: Change the autogenerated stub
	}
}